# Generated by Django 6.0.6 on 2026-06-13 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_delay', models.CharField(max_length=100)),
                ('material_shortage', models.CharField(max_length=100)),
                ('machine_downtime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('salary', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('vendor_name', models.CharField(max_length=100)),
                ('stock_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NXDrawingVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='nx_drawings/')),
                ('approval_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NXPartGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('bolt_diameter', models.FloatField()),
                ('bolt_length', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('output_type', models.CharField(default='NX 3D Model, PDF, STEP', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('machine_name', models.CharField(max_length=100)),
                ('shift', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('defect_count', models.IntegerField()),
                ('rework_status', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.employee')),
            ],
        ),
    ]
