# Generated by Django 6.0.6 on 2026-06-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('current_output', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='defect_count',
            field=models.IntegerField(default=0),
        ),
    ]
