# Generated by Django 6.0.6 on 2026-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_machine_alter_qualityinspection_defect_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='NXPartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('diameter', models.FloatField()),
                ('length', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
