# Generated by Django 6.0.6 on 2026-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_nxpartrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NXGeneratedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('nx_file', models.CharField(max_length=255)),
                ('step_file', models.CharField(max_length=255)),
                ('pdf_file', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
